---
  - include_vars: /home/showen/mint-build/static_variables.yml
  - name: Copying Sudo configuration...
    copy:                                                                                     
      src: /etc/sudoers 
      dest: "{{ BASE_DIR }}/roles/configurations/cinnamon-desktop/files/sudoers"
