---
  - include_vars: vars/main.yml
  - name: Initializing Flatpak...
    shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - name: Installing Applications [FLATPAK]...
    shell: flatpak install -y "{{ item }}"
    loop: "{{ FLATPAKS }}"  
