alias mint-backup="sudo ansible-playbook /home/showen/mint-build/backup.yml"
alias ssd-backup="~/showenotto/scripts/ssd-backup.sh"
alias log-out="cinnamon-session-quit --logout --force"
alias start-kali="VBoxManage startvm \"Kali Linux\""
alias stop-kali="VBoxManage controlvm \"Kali Linux\" poweroff"
alias save-kali="VBoxManage controlvm \"Kali Linux\" savestate"
