---
  - include_vars: /home/showen/mint-build/static_variables.yml
  - name: Backuping up Cinnamon desktop configuration...
    shell: su showen -c "dconf dump / > {{ BASE_DIR }}/roles/configurations/cinnamon-desktop/files/settings.dconf"
