---
  - name: Backing up Cinnamon Desktop configurations...
    shell: su showen -c "dconf dump / > /home/showen/mint-build/roles/configurations/cinnamon-desktop/files/settings.dconf"

  - name: Backing up redshift configurations...
    copy:
      src: /home/showen/.config/redshift.conf
      dest: /home/showen/mint-build/roles/configurations/cinnamon-desktop/files/redshift.conf
