---
  - name: Setting zsh as the default shell...
    command:
      cmd: chsh -s /bin/zsh showen
    become: true

  - name: Configuring zsh...
    copy:
      src: /home/showen/mint-build/roles/configurations/zsh/files/.zshrc
      dest: /home/showen/.zshrc
      owner: showen
      group: showen
      mode: '0644'
    become: true
