---
  - include_vars: /home/showen/mint-build/static_variables.yml
  - name: Installing Zsh...
    shell: |
      sudo apt install zsh zsh-syntax-highlighting zsh-autosuggestions -y
  - name: Setting Zsh as default shell...
    shell: echo "{{ PASSWD }}" | su showen -c 'chsh -s /bin/zsh'
  - name: Setting Zsh configurations...
    copy:
        src: "{{ BASE_DIR }}/roles/configurations/zsh/files/.zshrc"
        dest: /home/showen/.zshrc
    become: true


