---
  - name: Installing zsh...
    apt:
      name: zsh
      state: latest
  - name: Copying zsh configuration file...
    copy:
        src: /home/showen/mint-build/roles/configurations/zsh/files/.zshrc
        dest: /home/showen/.zshrc
    become: true


