---
  - name: Restoring Cinnamon desktop configurations...
    copy: 
      src: /home/showen/mint-build/roles/configurations/cinnamon-desktop/files/settings.dconf
      dest: /home/showen/.config/dconf/user
