---
  - name: Configuring Cinnamon Desktop...
    shell: su showen -c "dconf load / < /home/showen/mint-build/roles/configurations/cinnamon-desktop/files/settings.dconf"
    become: true

  - name: Configuring redshift...
    copy:
      src: /home/showen/mint-build/roles/configurations/cinnamon-desktop/files/redshift.conf
      dest: /home/showen/.config/redshift.conf
      owner: showen
      group: showen
      mode: '0644'


