---
  - include_vars: vars/main.yml
  - name: Installing Visual Studio Code...
    shell: flatpak install -y flathub com.visualstudio.code
  - name: "Installing SDK Extension: {{ item }}..."
    shell: |
      flatpak install -y "{{ item }}"
    loop: "{{ SDK_EXTENSIONS }}" 
    become: true
    become_user: showen

