---
  - name: Installing Tmux...
    apt:
      name: tmux
      state: present
  - name: Copying tmux configuration file...
    copy:
      src: /home/showen/mint-build/roles/configurations/tmux/files/tmux.conf
      dest: /etc/tmux.conf
    become: true
